services:
  postgres:
    image: postgres:16-alpine
    container_name: prototype_me_db
    environment:
      POSTGRES_USER: prototype
      POSTGRES_PASSWORD: prototype
      POSTGRES_DB: prototype_me
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
