import Foundation
import GRDB

/// Manages the local cache of server-authored periodic reviews.
/// Reviews are read-only: generated by backend cron, fetched and cached locally.
final class PeriodicReviewService: Sendable {

    private let db: DatabaseManager
    private let apiClient: APIClient

    init(db: DatabaseManager, apiClient: APIClient) {
        self.db = db
        self.apiClient = apiClient
    }

    // MARK: - Fetch & Cache

    /// Fetches reviews from the backend and merges them into the local cache.
    /// Matches on (period, periodStart) so a regenerated review (new id) replaces
    /// the old cached row for the same week/month. Does NOT delete local rows
    /// missing from the server response — that would break pagination.
    @discardableResult
    func refreshFromServer() async throws -> [PeriodicReview] {
        let reviews: [PeriodicReview] = try await apiClient.get("/v1/ai/reviews")
        try await mergeReviews(reviews)
        return reviews
    }

    // MARK: - Local cache writes

    private func mergeReviews(_ reviews: [PeriodicReview]) async throws {
        try await db.dbQueue.write { db in
            for review in reviews {
                // Remove any existing local row for the same (period, periodStart) — handles
                // regenerated reviews that arrive with a new id.
                try PeriodicReview
                    .filter(Column("period") == review.period && Column("periodStart") == review.periodStart)
                    .deleteAll(db)
                try review.insert(db)
            }
        }
    }
}
